#!/bin/bash
DIRNAME=`dirname "$1"`
BASENAME=`basename "$1"`

# TMP must be absolute!
TMP=/tmp/md_view_tmp.html

function generate_html {
    rm -f $TMP
    echo '<!DOCTYPE html>' > $TMP
    echo '<html lang="en"' >> $TMP
    echo '<head>' >> $TMP
    echo '<meta charset="utf-8" />' >> $TMP
    echo "<title>$1 - Markdown Preview Window</title>" >> $TMP
    echo '<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML">' >> $TMP
    echo 'MathJax.Hub.Config({jax: ["input/TeX","output/HTML-CSS"], displayAlign: "left", tex2jax: {inlineMath: [["$","$"]], displayMath: [["$$","$$"]], skipTags: ["script","noscript","style","textarea","pre","code"], processEnvironments: true }});' >> $TMP
    echo '</script>' >> $TMP
    echo '</head>' >> $TMP
    echo '<body>' >> $TMP
    cd "$DIRNAME"
    Markdown.pl --html4tags "$BASENAME" >> $TMP
    cd - >> /dev/null
    echo '</body>' >> $TMP
    echo '</html>' >> $TMP
}

function usage {
    echo -e "MDM - The Markdown Math Viewer 0.1 - Copyright (c) 2018 Szymon Wrozynski"
    echo -e "Licensed under the MIT License. More details here: https://github.com/szw/md"
    echo -e "Usage: $0 [file_name [target_name]]"
}

if [ -z "$1" ]; then
    usage
else
    generate_html
    if [ -z "$2" ]; then
        if [ $(uname -s) = "Darwin" ]; then
            open $TMP
        else
            xdg-open $TMP
        fi
    else
        mv $TMP $2
    fi
fi
